project:
  type: website
  output-dir: _site

website:
  title: "Luke's Website"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd

format:
  html:
    theme: cosmo
    toc: true
